### ISSUE TITLE
Changing roles

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/git-intro-activity#5]
Should we suggest that participants pair with someone who is using the same platform?

**Comment by burdged** [comment]
Should we include the changing of roles in the activity?

**Comment by kussmaul** [comment]
I like pairs using the same platform, when possible. Yes, pairs should be able to switch back and forth. We could even make it a game - a alarm that rings at random intervals, at which point pairs must switch.

**Comment by StoneyJackson** [comment]
This and #4 (team size) are related and probably need to be resolved together.

Decided:

- 2-person teams will be the default size.
- Folks should team team up with someone who uses the same platform (e.g., windows, osx, linux, etc.)

Questions:

1. What are the roles of the 2-person teams? Pair-programming roles: pilot and co-pilot? Pilot manipulates the local repository using git? Co-pilot reads each question and records team's answer?
2. What do we do with the odd person? Form a 3-person team, or work alone? I would prefer the 3-person team.
3. What are the roles for the odd person team? Assuming a 3-person team: pilot, reader/recorder, and QA?
4. How and when should we switch roles in teams? In my classes I set a timer and switch every 20 minutes. This also has the advantage of making teams aware of the passage of time and provides a natural moment to make announcements. Other options: switch after every N questions, place markers in the activities. Of those two, I prefer the every-N-questions approach because it would be easier to maintain as this activity evolves. Of all of these options, the timer is my favorite.
5. What happens when roles are switched? Do they switch seats/computers? If not, how do they carry on the team's work in the local git repository. So I think this is the answer. I pose the question in case I'm missing something.

**Comment by kussmaul** [comment]
2,3: plan for pairs, and one of us can join a pair if needed. Consider how strongly to insist on pairs - suppose 3 people from one school really want to work together.
4: switching at arbitrary (or even random) time emphasizes pair programming & collaboration (working together) vs. cooperation (divide & conquer).

**Comment by StoneyJackson** [comment]
@kussmaul Thanks for the feedback!

2,3: We could have a facilitator join the odd-person-out. However, if possible, the facilitator instructions in this activity should work in classes that have only one facilitator. And I wouldn't recommend a facilitator to embed with a student if s/he is the sole facilitator. So, I think I've convinced myself that we need instructions/roles for 3-person teams, and add a note for instructors that if you have more than one facilitators they could embed a facilitator with the team.

4: Good point. Let's go with rotation at intervals.

OK, I think I know what to do now:

- Form teams of 2 based on common platform (e.g., Windows, OSX, etc.)
- Odd-person-out joins a team of 2; or if there is enough facilitators, one facilitator teams up with odd-person-out.
- 2-person team roles:
  - Pilot - Manipulate git for the team
  - Co-pilot - Read instructions aloud and record team's responses
- 3-person team roles:
  - Pilot - same as 2-person
  - Co-pilot - same as 2-person
  - Quality Assurance (QA) - help ensure that pilot is carrying out operations correctly and that the answers recorded by co-pilot are clear.
- Roles will rotate regularly. Your facilitator will let you know when to rotate roles.

**Comment by burdged** [comment]
Sorry, to jump in on the conversation so late. I was away. I've never used the terms "pilot" and "co-pilot". I've always used "driver" and "navigator". I just did a search on "pair programming roles" and the first four results were for "driver" and "navigator" (or "observer"). I would prefer to use the commonly used terms.
I am fine with the descriptions of the roles as outlined above. 
I am also fine with rotations occurring at unknown intervals. I don't think I would like frequent rotations (more than two in an hour), but would be willing to try it.

**Comment by burdged** [comment]
I'm wondering if we might have time to allow the teams to reflect on work they've done and ask questions prior to a rotation. I think it is important to dispel any misconceptions before they are allowed to persist for too long. I know that the facilitator(s) can address questions while they work, but often good questions (and answers) are beneficial to all (rather than just the team who asked the question).

**Comment by StoneyJackson** [comment]
OK. Kept standard pair programming terminology. Other changes done.
